package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Dark Theme Colors (Dark Blue Style)
val DarkBackground = Color(0xFF0A1128)
val DarkSurface = Color(0xFF14213d)
val DarkPrimary = Color(0xFF4ea8de)
val DarkOnPrimary = Color(0xFF000000)
val DarkPrimaryContainer = Color(0xFF00509d)
val DarkOnPrimaryContainer = Color(0xFFe0fbfc)
val DarkSecondary = Color(0xFF7b2cbf)
val DarkOnSecondary = Color(0xFFFFFFFF)
val DarkSurfaceVariant = Color(0xFF243b6b)
val DarkOnSurfaceVariant = Color(0xFF90e0ef)
val DarkOnBackground = Color(0xFFFFFFFF)
val DarkOnSurface = Color(0xFFFFFFFF)
val DarkOutline = Color(0xFF4ea8de)
val DarkError = Color(0xFFd90429)
val DarkErrorContainer = Color(0xFFef233c)
val DarkOnError = Color(0xFFFFFFFF)
val DarkOnErrorContainer = Color(0xFFFFFFFF)

// Light Theme Colors (White and Red Style)
val LightBackground = Color(0xFFFFFFFF)
val LightSurface = Color(0xFFf8f9fa)
val LightPrimary = Color(0xFFd90429)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFffbba0)
val LightOnPrimaryContainer = Color(0xFF800000)
val LightSecondary = Color(0xFFef233c)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSurfaceVariant = Color(0xFFe9ecef)
val LightOnSurfaceVariant = Color(0xFF2b2d42)
val LightOnBackground = Color(0xFF000000)
val LightOnSurface = Color(0xFF000000)
val LightOutline = Color(0xFF8d99ae)
val LightError = Color(0xFFd90429)
val LightErrorContainer = Color(0xFFffbba0)
val LightOnError = Color(0xFFFFFFFF)
val LightOnErrorContainer = Color(0xFF800000)
